name: 'Python Multiply Numbers'

description: 'Custom action to multiply two numbers'
 
inputs:
  num1:
    description: 'First number'
    required: true
  num2:
    description: 'Second number'
    required: true
 
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Python Code
      shell: bash
      run: |
        cd ../../
        cd _actions/RameshGithubActions/CusAct1_Python/v24
        python3 src/main.py
