name: 'Python Multiply Numbers'

description: 'Custom action to multiply two numbers'
 
runs:
  using: 'docker'
  image: 'python:3.12'
 
inputs:
  num1:
    description: 'First number'
    required: true
  num2:
    description: 'Second number'
    required: true
 
outputs:
  result:
    description: 'Sum of the two numbers'
