name: 'Python Multiply Numbers'

description: 'Custom action to multiply two numbers'
 
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Python Code
      shell: bash
      run: |
        cd ../../
        cd _actions/RameshGithubActions/CusAct1_Python/v26
        python3 src/main.py
