name: 'Python Multiply Numbers'

description: 'Custom action to multiply two numbers'
 
inputs:
  num1:
    description: 'First number'
    required: true
  num2:
    description: 'Second number'
    required: true
 
runs:
  using: 'composite'
  steps:
    - name: Check files
      shell: bash
      run: |
        ls
        pwd
        cd ..
        ls
    
    - name: Run Python Code
      shell: bash
      run: python3 src/main.py

